name: Bug Report
description: Report a bug or unexpected behavior
labels: [ bug ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: When I do X, Y happens instead of Z...
    validations:
      required: true

  - type: textarea
    id: reproducing
    attributes:
      label: Steps to Reproduce
      description: Clear steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
      render: bash
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Message/Stacktrace
      description: If applicable, paste the error message or stacktrace here
      render: shell

  - type: input
    id: web-browser
    attributes:
      label: Web Browser
      description: What web browser are you using?
      placeholder: e.g. Chrome, Firefox, Safari
    validations:
      required: true

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have searched existing issues and this bug hasn't been reported yet
          required: true
        - label: I am running the latest version and the bug still exists
          required: true
        - label: This is a genuine bug and not caused by my modifications
          required: true